[dependencies.migration-utils]
path = "../utils"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.v3]
path = "../v3"

[lib]

[package]
edition = "2021"
name = "v4"
version = "0.1.0"
