[dependencies.migration-utils]
path = "../utils"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.v4]
path = "../v4"

[lib]

[package]
edition = "2021"
name = "v5"
version = "0.1.0"
